// Auto-generated by Supabase CLI. Do not edit manually.
// Regenerate after migrations: npm run types:gen

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      employees: {
        Row: {
          id: string
          auth_id: string | null
          employee_code: string
          first_name: string
          last_name: string
          email: string
          phone: string | null
          personal_email: string | null
          date_of_birth: string | null
          gender: 'male' | 'female' | 'other' | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          pincode: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          department_id: string | null
          designation_id: string | null
          reporting_manager_id: string | null
          role: 'owner' | 'hr' | 'employee' | 'system_admin'
          employment_type: 'full_time' | 'part_time' | 'contract' | 'intern'
          employment_status: 'active' | 'inactive' | 'terminated' | 'future_joiner'
          join_date: string | null
          exit_date: string | null
          probation_end_date: string | null
          current_salary: number | null
          photo_url: string | null
          previous_employee_id: string | null
          is_first_login: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['employees']['Row']>
        Update: Partial<Database['public']['Tables']['employees']['Row']>
        Relationships: []
      }
      departments: {
        Row: {
          id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['departments']['Row']>
        Update: Partial<Database['public']['Tables']['departments']['Row']>
        Relationships: []
      }
      designations: {
        Row: {
          id: string
          name: string
          department_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['designations']['Row']>
        Update: Partial<Database['public']['Tables']['designations']['Row']>
        Relationships: []
      }
      attendance_records: {
        Row: {
          id: string
          employee_id: string
          date: string
          check_in_time: string | null
          check_out_time: string | null
          total_hours: number | null
          overtime_hours: number | null
          status: 'present' | 'absent' | 'half_day' | 'on_leave' | 'holiday' | 'work_from_home' | 'weekly_off' | 'incomplete' | null
          is_late: boolean
          is_wfh: boolean
          is_geo_flagged: boolean
          is_manually_entered: boolean
          manual_entry_reason: string | null
          manual_entry_by: string | null
          check_in_lat: number | null
          check_in_lng: number | null
          check_out_lat: number | null
          check_out_lng: number | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['attendance_records']['Row']>
        Update: Partial<Database['public']['Tables']['attendance_records']['Row']>
        Relationships: []
      }
      leave_types: {
        Row: {
          id: string
          name: string
          code: string
          accrual_type: 'monthly' | 'yearly' | 'manual' | 'none'
          accrual_days: number
          max_carry_forward_days: number
          carry_forward_expiry_months: number | null
          max_consecutive_days: number | null
          min_notice_days: number
          is_paid: boolean
          requires_attachment: boolean
          applicable_gender: 'male' | 'female' | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['leave_types']['Row']>
        Update: Partial<Database['public']['Tables']['leave_types']['Row']>
        Relationships: []
      }
      leave_balances: {
        Row: {
          id: string
          employee_id: string
          leave_type_id: string
          year: number
          opening_balance: number
          carry_forward_amount: number
          carry_forward_expiry: string | null
          accrued: number
          taken: number
          pending: number
          adjusted: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['leave_balances']['Row']>
        Update: Partial<Database['public']['Tables']['leave_balances']['Row']>
        Relationships: []
      }
      leave_applications: {
        Row: {
          id: string
          employee_id: string
          leave_type_id: string
          from_date: string
          to_date: string
          working_days_count: number
          is_half_day: boolean
          half_day_period: 'morning' | 'afternoon' | null
          reason: string | null
          attachment_path: string | null
          status: 'pending' | 'approved' | 'rejected' | 'cancelled'
          reviewed_by: string | null
          reviewed_at: string | null
          reviewer_comment: string | null
          escalated_to: string | null
          escalated_at: string | null
          cancellation_requested: boolean
          cancellation_requested_at: string | null
          cancellation_reason: string | null
          cancelled_by: string | null
          cancelled_at: string | null
          applied_at: string
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['leave_applications']['Row']>
        Update: Partial<Database['public']['Tables']['leave_applications']['Row']>
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          recipient_id: string
          title: string
          body: string
          type: string
          reference_id: string | null
          reference_table: string | null
          is_read: boolean
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['notifications']['Row']>
        Update: Partial<Database['public']['Tables']['notifications']['Row']>
        Relationships: []
      }
      app_config: {
        Row: {
          key: string
          value: string
          description: string | null
          updated_by: string | null
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['app_config']['Row']>
        Update: Partial<Database['public']['Tables']['app_config']['Row']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      get_my_role: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
