-- Create the employee-documents storage bucket for employee document uploads.
-- This bucket stores PDF, JPEG, and PNG files uploaded via the upload-document
-- Edge Function. The bucket is private (not publicly accessible) — files are
-- accessed only via presigned URLs generated by the generate-presigned-url
-- Edge Function.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'employee-documents',
  'employee-documents',
  false,
  5242880,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do nothing;

-- Storage RLS: only service-role (Edge Functions) can manage objects.
-- Users access files via presigned URLs, never directly.
drop policy if exists "employee_documents_select" on storage.objects;
create policy "employee_documents_select" on storage.objects
  for select using (
    bucket_id = 'employee-documents'
    and (auth.role() = 'service_role')
  );

drop policy if exists "employee_documents_insert" on storage.objects;
create policy "employee_documents_insert" on storage.objects
  for insert with check (
    bucket_id = 'employee-documents'
    and (auth.role() = 'service_role')
  );

drop policy if exists "employee_documents_update" on storage.objects;
create policy "employee_documents_update" on storage.objects
  for update using (
    bucket_id = 'employee-documents'
    and (auth.role() = 'service_role')
  );

drop policy if exists "employee_documents_delete" on storage.objects;
create policy "employee_documents_delete" on storage.objects
  for delete using (
    bucket_id = 'employee-documents'
    and (auth.role() = 'service_role')
  );
